'use client';

import { AppSidebar } from '@/components/common/AppSidebar';
import type { MenuItem } from '../types/Admin';
import {
  LayoutDashboard,
  Package,
  ShoppingBag,
  Users,
  Store,
  Settings,
  BarChart3,
  Tag,
  Truck,
  MessageCircle,
  Star,
  DollarSign,
  FileText,
  Bell,
  HelpCircle,
  LogOut,
  ChevronDown,
  ChevronRight,
  PlusCircle,
  ListOrdered,
  Wallet,
  TrendingUp,
  Percent,
  Shield,
  Eye,
  Clock,
  Archive,
  Download,
  Upload,
  CreditCard,
  Gift,
  MapPin,
  User,
  Home,
  Briefcase,
  Sparkles,
  Zap,
  Menu,
  X,
  CheckCircle,
  AlertTriangle,
  Loader2,
  XCircle,
  Calendar,
  House,
  ShieldCheck,
  BookOpen,
  GraduationCap,
  Library,
  Video,
  CircleHelp,
  ClipboardList,
  School,
  UserPlus,
  Award,
  FileBadge,
  Send,
  Database,
  ClipboardCheck,
  LineChart,
  CalendarClock,
  Route,
  Plug,
  UserX,
  Tags,
  BadgeCheck,
} from 'lucide-react';

const iconMap = {
  BadgeCheck,
  UserX,
  Tags,
  ShieldCheck,
  LayoutDashboard,
  ShoppingBag,
  ListOrdered,
  Clock,
  Loader2,
  Truck,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Package,
  Users,
  Store,
  Settings,
  BarChart3,
  Tag,
  MessageCircle,
  Star,
  DollarSign,
  FileText,
  Bell,
  HelpCircle,
  LogOut,
  ChevronDown,
  ChevronRight,
  PlusCircle,
  Wallet,
  TrendingUp,
  Percent,
  Shield,
  Eye,
  Archive,
  Download,
  Upload,
  CreditCard,
  Gift,
  MapPin,
  User,
  Home,
  Briefcase,
  Sparkles,
  Zap,
  Menu,
  X,
  Calendar,
  House,

  BookOpen,
  GraduationCap,
  Library,
  Video,
  CircleHelp,
  ClipboardList,
  School,
  UserPlus,
  Award,
  FileBadge,
  Send,
  Database,
  ClipboardCheck,
  LineChart,
  CalendarClock,
  Route,
  Plug,
};
export type IconName = keyof typeof iconMap;
export const superAdminMenuItems: MenuItem[] = [
  {
    title: 'Beranda',
    icon: 'House',
    href: '/',
    exact: true,
  },
  {
    title: 'Dashboard',
    icon: 'LayoutDashboard',
    href: '/admin',
    exact: true,
  },
  {
    title: 'Manajemen User',
    icon: 'Users',
    href: '/admin/users',
    submenu: [
      { title: 'Semua User', href: '/admin/users', icon: 'Users', exact: true },
      { title: 'Tambah User', href: '/admin/users/create', icon: 'UserPlus' },
      // { title: 'Instructor', href: '/admin/users?role=instructor', icon: 'GraduationCap' },
      // { title: 'Student', href: '/admin/users?role=student', icon: 'User' },
      // { title: 'User Nonaktif', href: '/admin/users?status=inactive', icon: 'UserX' },
    ],
  },
  //   {
  //     title: 'Kursus',
  //     icon: 'BookOpen',
  //     href: '/super-admin/courses',
  //     submenu: [
  //       { title: 'Semua Kursus', href: '/super-admin/courses', icon: 'BookOpen', exact: true },
  //       { title: 'Draft', href: '/super-admin/courses?status=draft', icon: 'FileText' },
  //       { title: 'Published', href: '/super-admin/courses?status=published', icon: 'CheckCircle' },
  //       { title: 'Archived', href: '/super-admin/courses?status=archived', icon: 'Archive' },
  //       { title: 'Kategori Kursus', href: '/super-admin/courses/categories', icon: 'Tags' },
  //     ],
  //   },
  //   {
  //     title: 'Materi Pembelajaran',
  //     icon: 'Library',
  //     href: '/super-admin/contents',
  //     submenu: [
  //       { title: 'Semua Materi', href: '/super-admin/contents', icon: 'Library', exact: true },
  //       { title: 'Video', href: '/super-admin/contents?type=video', icon: 'Video' },
  //       { title: 'Dokumen', href: '/super-admin/contents?type=document', icon: 'FileText' },
  //       { title: 'Quiz', href: '/super-admin/contents?type=quiz', icon: 'CircleHelp' },
  //       { title: 'Assignment', href: '/super-admin/contents?type=assignment', icon: 'ClipboardList' },
  //     ],
  //   },
  //   {
  //     title: 'Kelas',
  //     icon: 'School',
  //     href: '/super-admin/classes',
  //     submenu: [
  //       { title: 'Semua Kelas', href: '/super-admin/classes', icon: 'School', exact: true },
  //       { title: 'Aktif', href: '/super-admin/classes?status=active', icon: 'CheckCircle' },
  //       { title: 'Selesai', href: '/super-admin/classes?status=completed', icon: 'BadgeCheck' },
  //       { title: 'Terjadwal', href: '/super-admin/classes?status=scheduled', icon: 'CalendarClock' },
  //     ],
  //   },
  //   {
  //     title: 'Enrollment',
  //     icon: 'UserPlus',
  //     href: '/super-admin/enrollments',
  //     submenu: [
  //       { title: 'Semua Enrollment', href: '/super-admin/enrollments', icon: 'UserPlus', exact: true },
  //       { title: 'Aktif', href: '/super-admin/enrollments?status=active', icon: 'CheckCircle' },
  //       { title: 'Pending', href: '/super-admin/enrollments?status=pending', icon: 'Clock' },
  //       { title: 'Selesai', href: '/super-admin/enrollments?status=completed', icon: 'BadgeCheck' },
  //     ],
  //   },
  //   {
  //     title: 'Sertifikat',
  //     icon: 'Award',
  //     href: '/super-admin/certificates',
  //     submenu: [
  //       { title: 'Semua Sertifikat', href: '/super-admin/certificates', icon: 'Award', exact: true },
  //       { title: 'Template Sertifikat', href: '/super-admin/certificates/templates', icon: 'FileBadge' },
  //       { title: 'Terbitkan Sertifikat', href: '/super-admin/certificates/issue', icon: 'Send' },
  //       { title: 'Verifikasi Sertifikat', href: '/super-admin/certificates/verify', icon: 'ShieldCheck' },
  //     ],
  //   },
  //   {
  //     title: 'Assessment',
  //     icon: 'ClipboardCheck',
  //     href: '/super-admin/assessments',
  //     submenu: [
  //       { title: 'Quiz', href: '/super-admin/assessments/quizzes', icon: 'CircleHelp' },
  //       { title: 'Assignment', href: '/super-admin/assessments/assignments', icon: 'ClipboardList' },
  //       { title: 'Bank Soal', href: '/super-admin/assessments/question-bank', icon: 'Database' },
  //       { title: 'Penilaian', href: '/super-admin/assessments/grading', icon: 'ClipboardCheck' },
  //     ],
  //   },
  //   {
  //     title: 'Laporan',
  //     icon: 'BarChart3',
  //     href: '/super-admin/reports',
  //     submenu: [
  //       { title: 'Ringkasan', href: '/super-admin/reports', icon: 'TrendingUp', exact: true },
  //       { title: 'Progress Siswa', href: '/super-admin/reports/student-progress', icon: 'LineChart' },
  //       { title: 'Performa Kursus', href: '/super-admin/reports/course-performance', icon: 'BarChart3' },
  //       { title: 'Aktivitas Instructor', href: '/super-admin/reports/instructors', icon: 'GraduationCap' },
  //       { title: 'Ekspor Data', href: '/super-admin/reports/export', icon: 'Download' },
  //     ],
  //   },
  //   {
  //     title: 'Pengaturan LMS',
  //     icon: 'Settings',
  //     href: '/super-admin/settings',
  //     submenu: [
  //       { title: 'General', href: '/super-admin/settings', icon: 'Settings', exact: true },
  //       { title: 'Role & Permission', href: '/super-admin/settings/roles', icon: 'Shield' },
  //       { title: 'Learning Path', href: '/super-admin/settings/learning-paths', icon: 'Route' },
  //       { title: 'Notifikasi', href: '/super-admin/settings/notifications', icon: 'Bell' },
  //       { title: 'Integrasi', href: '/super-admin/settings/integrations', icon: 'Plug' },
  //     ],
  //   },
];
import { useSession } from 'next-auth/react';
export function AppSidebarAdmin() {
  const { data: session } = useSession();

  return (
    <AppSidebar
      menuItems={superAdminMenuItems}
      user={{
        name: session?.user?.name || 'Seller',
        roleLabel: 'Seller',
        avatar: session?.user?.image,
        fallback: 'BS',
      }}
      iconMap={iconMap}
    />
  );
}
